name = "isuku"
compatibility_date = "2024-11-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 データベース
[[d1_databases]]
binding = "DB"
database_name = "isk-db"
database_id = "cafa2521-13d3-4ecd-b2dc-99837877487d"

# R2 バケット
[[r2_buckets]]
binding = "R2"
bucket_name = "isk-media"

# 環境変数
[vars]
NEXT_PUBLIC_SITE_URL = "https://isk.masa86.com"
R2_PUBLIC_URL = "https://isk-media.masa86.com"
